---
apiVersion: v1
kind: Service
metadata:
  name: kubeapp
  namespace: kubeapp
spec:
  type: NodePort
  selector:
    app: kubeapp
  ports:
  - name: port-1
    nodePort: 31484
    port: 80
    protocol: TCP
    targetPort: 3000
status:
  loadBalancer: {}
