apiVersion: v1
kind: Namespace
metadata:
  name: nginxapp
---
kind: Service
apiVersion: v1
metadata:
  name: nginxapp
  namespace: nginxapp
spec:
  type: ClusterIP
  selector:
    app: nginxapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxapp
  namespace: nginxapp
spec:
  selector:
    matchLabels:
      app: nginxapp
  replicas: 10
  template:
    metadata:
      labels:
        app: nginxapp
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
